export const GET_CHOCOLATES = "GET_CHOCOLATES";
export const GET_CHOCOLATES_SUCCESS = "GET_CHOCOLATES_SUCCESS";
export const GET_CHOCOLATES_FAILURE = "GET_CHOCOLATES_FAILURE";

//types

export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE";

export const GET_BRANDDETAIL = "GET_BRANDDETAIL";
export const GET_BRAND_DETAIL_SUCCESS = "GET_BRAND_DETAIL_SUCCESS";
// export const GET_BRANDDEC_SUCCESS = "GET_BRANDDEC_SUCCESS";
export const GET_BRANDDETAIL_FAILURE = "GET_BRANDDETAIL_FAILURE";

//chocolates Desc

export const GET_CHOCOLATE_DESC = "GET_CHOCOLATE_DESC";
export const GET_CHOCOLATE_DESC_SUCCESS = "GET_CHOCOLATE_DESC_SUCCESS";
export const GET_CHOCOLATE_DESC_FAILURE = "GET_CHOCOLATE_DESC_FAILURE";

//
export const INPUT_CHANGE = "INPUT_CHANGE";

export const GET_SIGNUP = "GET_SIGNUP";
export const GET_SIGNUP_SUCCESS = "GET_SIGNUP_SUCCESS";
export const GET_SIGNUP_FAILURE = "GET_SIGNUP_FAILURE";

export const GET_LOGIN = "GET_LOGIN";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILURE = "GET_LOGIN_FAILURE";

export const GET_SEARCH = "GET_SEARCH";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAILURE = "GET_SEARCH_FAILURE";
